// Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
// By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
// find the sum of the even-valued terms.
#include <iostream>
using namespace std;

int main(int agr, char **argv) {
    int fidNums [] = {1,1, 0};
    int sum = 0;


    for(; fidNums[2] < 4000000; fidNums[2] = fidNums[0] + fidNums[1]) {
        fidNums[0] = fidNums[1];
        fidNums[1] = fidNums[2];

        if ( fidNums[2] % 2 == 0) {
            sum = sum + fidNums[2];
      } 
    }
    cout << "The sum of the numbers is " << sum;

    return 0;
}
